### PR TITLE
Add AVIF support

### PR DESCRIPTION
**Pull request by RReverser**
Note this currently doesn't port upstream tests; not sure if I'll get around to that, but figured I'll submit PR anyway.

### CODE REVIEW

**Comment by RReverser** [comment]
Converted to draft because, aside from tests, this clearly needs more work to be supported as a dynamic module.

**Comment by kleisauke** [comment]
Great! I was able to support this as a dynamic module and also added some test coverage for this (by porting libvips' AVIF tests).
https://github.com/RReverser/wasm-vips/compare/avif...kleisauke:wasm-vips:avif-RReverser

**Comment by RReverser** [comment]
> Great! I was able to support this as a dynamic module and also added some test coverage for this (by porting libvips' AVIF tests).

Feel free to push directly to my PR, might be easier than tracking across different branches.

**Comment by RReverser** [comment]
Or, alternatively, I can close mine and you open yours. Whichever is easier.

**Comment by kleisauke** [comment]
> Feel free to push directly to my PR, might be easier than tracking across different branches.

I just pushed it to the branch associated with this PR.

**Review by kleisauke — APPROVED** [review]
Thank you! This will be in v0.0.5.

**Pull request merged**
